name: Example Script Resource Model
rundeckPluginVersion: 2.0
author: Rundeck Dev
description: Describe your plugin here
rundeckCompatibilityVersion: 3.x
targetHostCompatibility: unix
license: Apache 2.0
tags:
    - script
    - ResourceModelSource
date: 2026-02-03T22:50:09.472848Z
version: 1.0.0
providers:
    - name: example-script-resource-model
      service: ResourceModelSource
      title: Example Script Resource Model
      description: The description of example-script-resource-model plugin
      plugin-type: script
      script-interpreter: /bin/bash
      script-file: resource
      resource-format: resourcejson
      config:
        - type: String
          name: customtags
          title: 'Example Custom Tags'
          description: 'Add Custom Tags'
          required: true
        - type: Select
          name: exampleSelect
          title: ExampleSelect
          description: 'Node Filter'
          default: app
          values:
            - app
            - db
            - www
        - type: Boolean
          name: running
          title: Just running nodes?
          description: 'Filter by running nodes'
          renderingOptions:
            groupName: 'Config'