name: Example Script File Copier
rundeckPluginVersion: 2.0
author: Rundeck Dev
description: Describe your plugin here
rundeckCompatibilityVersion: 3.x
targetHostCompatibility: unix
license: Apache 2.0
tags:
    - script
    - FileCopier
date: 2026-02-03T22:11:08.799506Z
version: 1.0.0
providers:
    - name: example-script-file-copier
      service: FileCopier
      title: Example Script File Copier
      description: The description of example-script-file-copier plugin
      plugin-type: script
      script-interpreter: /bin/bash
      script-file: filecopier
      script-args: ${file-copy.file} ${file-copy.destination}
      config:
        - type: String
          name: example
          title: 'Example String'
          description: 'Example String'
          required: true
        - type: Select
          name: exampleSelect
          title: ExampleSelect
          description: 'Example Select'
          default: Beige
          values:
            - Blue
            - Beige
            - Black
        - type: Boolean
          name: dry_run
          title: Dry Run?
          description: 'Just echo what would be done'
          default: true
          renderingOptions:
            groupName: 'Config'
        - type: String
          name: storageprivatekey
          title: Storage Private Key
          description: Access to storage private key example
          renderingOptions:
            selectionAccessor: "STORAGE_PATH"
            valueConversion: "STORAGE_PATH_AUTOMATIC_READ"
            storage-path-root: "keys"
            storage-file-meta-filter: "Rundeck-key-type=private"
        - type: String
          name: storagepassword
          title: Storage Password
          description: Access to storage password example
          renderingOptions:
            selectionAccessor: "STORAGE_PATH"
            valueConversion: "STORAGE_PATH_AUTOMATIC_READ"
            storage-path-root: "keys"
            storage-file-meta-filter: "Rundeck-data-type=password"